### ISSUE TITLE
Some questions...

### ISSUE THREAD

**Issue by cintiadr** [maccyber/dockerhub-webhook#28]
I know this is not an issue per si, but I'd like to ask a few questions and there's no easy way to contact you :)

First, I'd like to thank you for the awesome work. I've searched quite a lot for a ready-to-prod dockerhub-webhook service, and yours is by far the best I've found. 

But I'm running into some difficulties. 

1) I'm receiving 400 on _any_ callback call, for example: https://gist.github.com/cintiadr/0722625cedc4c79a4efe9ca3c74a41f6
I tried several different changes, tried to print the request and full response (https://github.com/cintiadr/dockerhub-webhook/commit/8046164e9aa2b6f83dfb42553fc9a39d86526835) , tried to change the `target_url`. Is this working for you? Do you have any idea how to fix it? As I will have different webhooks on the same image, I believe that will prevent the next webhooks to be called. 

2) I would like to have bash and other basic commands, because deploying this app as a docker container is way too awesome to be ignored, but I want to have deploy scripts a little bit more complicated. Would you be willing to accept a pull request to add those things? If not, it's fine, I will then keep my own dockerfile. 

3) I need to set the tag and pass arguments to the script. So, when I push testhook:8.0 (not the others tags), I'd like to call 'hello.sh' with argument 'something'. 
```
module.exports = {
  'testhook:8.0': 'hello.sh something', 
}
```
Neither of those things are possible by now apparently. I will have multiple tags on the same image, deployed to different hosts, so the tag is very important. 
The arguments could be prevented having a wrapper script per repository, but it sounds quite of a silly workaround. 
Is there any chance you'd be able to implement something like that? :) My javascript-fu is pretty much nil, so I wouldn't be able to create a pull request.

But thanks for all the work.

**Comment by maccyber** [comment]
Thanks, awesome to see it being used.

Earlier I was out on the same quest as you - to find a good dockerhub-webhook service, but i couldn't find any (good). So decided to write my own.

Added some commits, I changed the lookup of repo names, so in ```scripts/index.js``` you now have to define the repo with namespace e.g.
```js
module.exports = {
  'cintiadr/testhook': 'hello.sh something', 
}
```

1. Got the same error, will look into it.
Added ability to disable callback to dockerhub see [config/index.js](https://github.com/maccyber/dockerhub-webhook/blob/master/config/index.js)
2. Send me a pull request and I'll merge it
3. Added ability to run script with parameters

I will look into tag-support.

**Comment by cintiadr** [comment]
I did more tests with the callback, and contrary to what the documentation said, it doesn't prevent other webhooks to be triggered. In fact, all webhooks will be triggered at the same time, and they are all showing as success anyway if you look at the webhook history (I suppose that's the 204 we are sending back). I have no idea how or if this callback is supposed to work. 
So, while it's a little bit weird, it's not a show stopper. 

About the bash: https://github.com/maccyber/dockerhub-webhook/pull/29
Thanks for the arguments! Even better, I can now even have file redirects:

```
module.exports = {
  'cintiadr/testhook': 'hello.sh something > /tmp/somefile', 
}
```

It's brilliant!

**Comment by cintiadr** [comment]
Based on https://forums.docker.com/t/webhook-pipelines-dont-wait-for-callback/5813/2 and https://forums.docker.com/t/webhook-callback-failed-400-client-error-when-using-autodeploy/10011/6 , I'd assume that it's broken for way more people. I couldn't create any curl command which allowed an update. 
Maybe it's now only available for paid repositories? 

Anyway, ignoring the callback works just fine for me.

**Comment by maccyber** [comment]
Ah, thanks for investigating this. I will disable callbacks by default until this is sorted out @ [hub-feedback #943](https://github.com/docker/hub-feedback/issues/943).

Cool with the bash-thingy.

**Comment by cintiadr** [comment]
Just to keep you (and whoever lands here from google search) in the loop, I'm using a wrapper script to see if there was a newer version of the tag I'm using on docker-compose file:

https://github.com/openmrs/openmrs-contrib-ansible-docker-compose/blob/master/files/dockerhub-webhook/scripts/deploy-compose-if-newer

It's not the smartest thing I've ever coded, but it does work and allow me to deploy it the way it is right now. 
In all fairness, the ability to only trigger a webhook on a certain tag is something that could be done in dockerhub itself.

**Comment by maccyber** [comment]
Rewrote the whole thing and added tag support to this [maccyber/micro-dockerhub-hook](https://github.com/maccyber/micro-dockerhub-hook).

Not well tested..
