### ISSUE TITLE
Problems with dockerhub and dockerhub-webhook

### ISSUE THREAD

**Issue by hurrrrricaaaaane** [maccyber/dockerhub-webhook#50]
Hey there,

I'm new on docker and I want to run your webhook. I've configured the dockerhub-webhook tool as mentioned in the documentation but it doesn't work.

I have a docker image which i push to https://hub.docker.com/ in my private free repo and til here everything is fine.
But after the push I would expect that the dockerhub-webhook server which is running on my devserver will print some outputs of the requests which should come in from the https://hub.docker.com/.

The problem is: No request, no reaction that anything happens of the side of https://hub.docker.com/.
Maybe you can advice me how to run these things?

Thanks & Best regards,
Josef

**Comment by maccyber** [comment]
Hi,

I've moved almost everything to [now](https://zeit.co/now), so this is not activly maintained anymore.

But yes, you should see something like [this](https://gist.github.com/maccyber/042467eac7a38b2d2cb639cb02c33f7f) in the logs of dockerhub-webhook.

.. and on the hub.docker.com -side you should see if the webhook has been triggered on *repo -> webhooks -> click the three dots beside the weebhook -> and "view history"*.

Although, i have not tried dockerhub-webhook with a *private repo*

To be of any assistance, I need more detailed information like
- Which "[Installation/running alternatives](https://github.com/maccyber/dockerhub-webhook#installation-alternatives)" are you using?
- Is the server/port you're running dockerhub-webhook on, accessible from the Internet?
- Have you configured the webhook url to your server like [configuration-on-docker-hub](https://github.com/maccyber/dockerhub-webhook#configuration-on-docker-hub)?
